### ISSUE TITLE
Yea Im having same issue.  As of now when I open the wallet, theres nothing in it.  And Im kind of trippin.

### ISSUE THREAD

**Issue by Tracex-sys** [PirateNetwork/lightwalletd#1]
Yea Im having same issue.  As of now when I open the wallet, theres nothing in it.  And Im kind of trippin.

_Originally posted by @bobdobalina33 in https://github.com/PirateNetwork/PirateWallet-Lite/issues/95#issuecomment-1075825867_

**Comment by kaks25** [comment]
Do you see your addresses? please post more details about your issue

**Comment by Tracex-sys** [comment]
![Screenshot_802](https://user-images.githubusercontent.com/65625306/206223379-cfd08817-9c27-452e-a94e-80c153feb3be.png)
Support, in the attachment, this is what is displayed, no addresses, nothing, except what you see. You will notice, there is "NO CONNECTION" displayed at bottom right hand side. I don't know how to re connect to PIRATE LITE WALLET 106 and am asking
support how to re connect to wallet. I have SEED PHRASE, but, this is a connection issue. 
                                                                                             Please advise,
                                                                                             Tracex-sys  (Charles Swank)

**Comment by kaks25** [comment]
Close and run the wallet again and dont close the mini window to let the wallet to sync, if doesnt show check your internet connection and the firewall
[
![Untitled](https://user-images.githubusercontent.com/65034388/206228014-0e624ef4-c136-4b1c-a147-e97c12e30485.png)
](url)

**Comment by Tracex-sys** [comment]
As I mentioned previously, there is no connection, therefore, I no longer get a drop down that implies syncing in progress as you show above. If it is syncing, I would be connected. If it is a firewall interference, how do I correct this to be able to connect to
PIRATE WALLET v-106?

**Comment by kaks25** [comment]
if you run a VPN try to turn it off, for the firewall here allow the app connection from the guide below
https://www.makeuseof.com/how-to-allow-apps-windows-firewall/
